In [1]:
import pandas as pd
import sqlite3 as sq
import matplotlib as mpl
from matplotlib import rcParams
import matplotlib.pyplot as plt
import numpy as np
import requests
pd.set_option('display.max_rows', 1000); pd.set_option('display.max_columns', 1000); pd.set_option('display.width', 1000)
pd.options.mode.chained_assignment = None
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)

In [2]:
data = pd.read_excel(r'G:\DATA\REQUESTS_CLIENTS\GNRC\20240215_UrbanSim_Update\Model Outputs\Small_Area.xlsx', sheet_name = None)

In [8]:
for sheet_name, df in data.items():
    print(f"Sheet Name: {sheet_name}")
    print(df.head())

Sheet Name: SUB-IP-EST2023-POP-47
  table with row headers in column A and column headers in rows 3 through 4 (leading dots indicate sub-parts)                     Unnamed: 1                          Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5
0  Annual Estimates of the Resident Population fo...                                                                                     NaN                                 NaN         NaN         NaN         NaN
1                                    Geographic Area                                                           April 1, 2020\nEstimates Base  Population Estimate (as of July 1)         NaN         NaN         NaN
2                                                NaN                                                                                     NaN                                2020      2021.0      2022.0      2023.0
3                              Adams city, Tennessee                                                                                     620                                 621       631.0       646.0       653.0
4                         Adamsville town, Tennessee                                                                                    2263                                2262      2255.0      2250.0      2276.0
Sheet Name: parcel lookup
   OBJECTID * Shape *  Join_Count  TARGET_FID  urbansim_r          X          Y       X_LP       Y_LP NAME  NAMELSAD   Shape_Length         Name Type
0      669347   Point           1      669346       15324 -87.013953  36.135439 -87.013953  36.135439  NaN  Cheatham  953969.243122  Peagram UGB  UGB
1      669350   Point           1      669349       15351 -87.011172  36.135244 -87.011172  36.135244  NaN  Cheatham  953969.243122  Peagram UGB  UGB
2      669352   Point           1      669351       15330 -87.013097  36.134054 -87.013097  36.134054  NaN  Cheatham  953969.243122  Peagram UGB  UGB
3      669353   Point           1      669352       15350 -87.009619  36.134734 -87.009619  36.134734  NaN  Cheatham  953969.243122  Peagram UGB  UGB
4      669354   Point           1      669353       15273 -87.012648  36.132675 -87.012648  36.132675  NaN  Cheatham  953969.243122  Peagram UGB  UGB
Sheet Name: Run 35 - parcel forecast 2023
     County City  Unnamed: 2  geo_level_id          x          y  units  households    jobs  household_population  Unnamed: 10  04/11/2025 run  Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17    County.1  Unnamed: 19
0  Cheatham    0         NaN             1 -87.080007   36.31388      2           2    7.23                  4.56          NaN             NaN          NaN          NaN          NaN          NaN          NaN          NaN    Cheatham          NaN
1  Cheatham    0         NaN             2 -87.247114  36.366981      0           0  116.98                  0.00          NaN             NaN          NaN          NaN          NaN          NaN          NaN          NaN           0          NaN
2  Cheatham    0         NaN             3 -87.026783  36.182776      1           1    0.22                  2.30          NaN             NaN          NaN          NaN          NaN          NaN          NaN          NaN  Montgomery          NaN
3  Cheatham    0         NaN             4 -87.116023  36.309677      2           2    1.54                  5.17          NaN             NaN          NaN          NaN          NaN          NaN          NaN          NaN         NaN          NaN
4  Cheatham    0         NaN             5 -87.130918  36.279787      0           0    0.00                  0.00          NaN             NaN          NaN          NaN          NaN          NaN          NaN          NaN     Dickson          NaN
Sheet Name: Run 35 - parcel forecast 2050
     County City  Unnamed: 2  geo_level_id          x          y  units  households    jobs  household_population  Unnamed: 10  04/11/2025 run
0  Cheatham    0         NaN             1 -87.080007   36.31388      3           3    7.22                  7.47          NaN             NaN
1  Cheatham    0         NaN             2 -87.247114  36.366981      0           0  117.30                  0.00          NaN             NaN
2  Cheatham    0         NaN             3 -87.026783  36.182776      1           1    0.54                  2.29          NaN             NaN
3  Cheatham    0         NaN             4 -87.116023  36.309677      2           2    2.30                  5.20          NaN             NaN
4  Cheatham    0         NaN             5 -87.130918  36.279787      0           0    0.10                  0.00          NaN             NaN
Sheet Name: SDC_TN_PL20_QuickStat_Place_160
   SUMLEV  LOGRECNO             GEOID  GEOCODE  STATE  PLACE PLACECC  PLACENS  AREALAND  AREAWATR             NAME    BASENAME                 Unnamed: 12  P0010001  P0010002  P0010003  P0010004  P0010005  P0010006  P0010007  P0010008  P0010009  P0020002  P0020003  P0020004  P0020005  P0020006  P0020007  P0020008  P0020009  P0020010  P0020011  P0030001  H0010001  H0010002  H0010003  P0050001  P0050002  P0050003  P0050004  P0050005  P0050006  P0050007  P0050008  P0050009  P0050010
0     160      7754  1600000US4700200  4700200     47    200      C1  2403062   6191502         0       Adams city       Adams       Adams city, Tennessee       624       595       553        22         7         2         0        11        29        16       608       582       550        22         5         2         0         3        26       490       250       232        18        19        19         0         0        19         0         0         0         0         0
1     160      7755  1600000US4700240  4700240     47    240      C1  2405121  18229644    123178  Adamsville town  Adamsville  Adamsville town, Tennessee      2265      2163      2076        60         2        10         0        15       102        41      2224      2141      2066        59         2        10         0         4        83      1755      1039       924       115       103       103         0         0       103         0         0         0         0         0
2     160      7756  1600000US4700440  4700440     47    440      C1  2405126   5687270         0       Alamo town       Alamo       Alamo town, Tennessee      2336      2174      1546       361         6         2         0       259       162       379      1957      1894      1515       361         1         2         0        15        63      1780       994       904        90       126       126        55         0        71         0         0         0         0         0
3     160      7757  1600000US4700540  4700540     47    540      C1  2403075  38844058   2372876       Alcoa city       Alcoa       Alcoa city, Tennessee     10978     10169      8355      1279        59       114         3       359       809       805     10173      9602      8146      1262        32       113         3        46       571      8372      4961      4632       329       119        78         0         0        78         0        41         0         0        41
4     160      7758  1600000US4700620  4700620     47    620      C1  2405130   5245013         0  Alexandria town  Alexandria  Alexandria town, Tennessee       981       926       870        38         6         2         0        10        55        12       969       914       860        38         6         2         0         8        55       762       476       420        56         0         0         0         0         0         0         0         0         0         0
Sheet Name: Summary_Base
            GIS                           ACS  2023 ACS TOTAL POPULATION EST  2023 UrbanSim HH POPULATION  Absolute  Percentage  2023 UrbanSim HH  2023 UrbanSim EMP  Unnamed: 8 Unnamed: 9    Unnamed: 10  Unnamed: 11
0         Adams         Adams city, Tennessee                            653                       610.90    -42.10   -0.064472             237.0             116.14         NaN        NaN            NaN          NaN
1  Ashland City  Ashland City town, Tennessee                           5586                      5102.26   -483.74   -0.086599            2307.0            8728.65         NaN        NaN            NaN          NaN
2   Belle Meade   Belle Meade city, Tennessee                           2594                      2932.11    338.11    0.130343            1126.0            1032.05         NaN   Cheatham  GQ Population        330.0
3    Berry Hill    Berry Hill city, Tennessee                           1840                      2123.00    283.00    0.153804            1464.0           18236.44         NaN   Davidson  GQ Population      23732.0
4     Brentwood     Brentwood city, Tennessee                          45265                     45519.26    254.26    0.005617           15435.0           77803.17         NaN    Dickson  GQ Population        767.0
Sheet Name: Summary_Growth
            GIS                           ACS  2023 UrbanSim EMP  2050 UrbanSim EMP  2023 UrbanSim HH  2050 UrbanSim HH  2023 UrbanSim HH POPULATION  2050 UrbanSim HH POPULATION  Absolute   Percent  Unnamed: 10  Unnamed: 11  Unnamed: 12 Unnamed: 13    Unnamed: 14  Unnamed: 15
0         Adams         Adams city, Tennessee             116.14             145.17             237.0             223.0                       610.90                       571.54    -39.36 -0.064430          NaN          NaN          NaN         NaN            NaN          NaN
1  Ashland City  Ashland City town, Tennessee            8728.65           10069.61            2307.0            1970.0                      5102.26                      4285.53   -816.73 -0.160072          NaN          NaN          NaN         NaN            NaN          NaN
2   Belle Meade   Belle Meade city, Tennessee            1032.05            1005.05            1126.0            1406.0                      2932.11                      3675.41    743.30  0.253503          NaN          NaN          NaN    Cheatham  GQ Population        330.0
3    Berry Hill    Berry Hill city, Tennessee           18236.44           22157.13            1464.0            1553.0                      2123.00                      2404.00    281.00  0.132360          NaN          NaN          NaN    Davidson  GQ Population      23732.0
4     Brentwood     Brentwood city, Tennessee           77803.17          120538.08           15435.0           18218.0                     45519.26                     53881.21   8361.95  0.183701          NaN          NaN          NaN     Dickson  GQ Population        767.0
Sheet Name: SmallArea
     Unnamed: 0                    Unnamed: 1 Decennial Census Unnamed: 3 Unnamed: 4 Census PEP UrbanSim Model Unnamed: 7 Unnamed: 8     Unnamed: 9    Unnamed: 10    Unnamed: 11 Unnamed: 12 Unnamed: 13 Net Change Unnamed: 15 Unnamed: 16
0           NaN                           NaN             2020        NaN        NaN       2023      2023 Base        NaN        NaN  Abs Variation  Pct Variation  2050 Forecast         NaN         NaN  2023-2050         NaN         NaN
1  Municipality                           NaN              MPA        Pop        HHs        Pop            Pop        HHs        EMP            Pop            Pop            Pop         HHs         EMP        Pop         HHs         EMP
2         Adams         Adams city, Tennessee              YES        624        232        653          610.9        237     116.14          -42.1      -0.064472         571.54         223      145.17   -0.06443   -0.059072    0.249957
3  Ashland City  Ashland City town, Tennessee               NO       5193       2145       5586        5102.26       2307    8728.65        -483.74      -0.086599        4285.53        1970    10069.61  -0.160072   -0.146077    0.153627
4   Belle Meade   Belle Meade city, Tennessee              YES       2901       1073       2594        2932.11       1126    1032.05         338.11       0.130343        3675.41        1406     1005.05   0.253503    0.248668   -0.026162
Sheet Name: Summary_w_UGB
     County              City            Growth  2023 POP  2050 POP  POP_DIFF  2023 HH  2050 HH  HH_DIFF  2023 EMP  2050 EMP  EMP_DIFF
0  Cheatham      Ashland City               NaN   5102.26   4285.53   -816.73     2307     1970     -337   8728.65  10069.61   1340.96
1  Cheatham  Kingston Springs               NaN   2673.06   3592.95    919.89     1084     1441      357   1032.21   1185.92    153.71
2  Cheatham            Pegram               NaN   1992.71   3139.99   1147.28      816     1271      455    499.37    612.60    113.23
3  Cheatham     Pleasant View               NaN   4853.94   8717.17   3863.23     1920     3349     1429   2761.52   2949.71    188.19
4  Cheatham               NaN  Ashland City UGB    431.13    327.77   -103.36      168      129      -39     22.25     68.28     46.03
Sheet Name: Run 35 - parcel forecast 23UGB
     County City Unnamed: 2  geo_level_id          x          y  units  households    jobs  household_population  Unnamed: 10  04/11/2025 run  Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17    County.1  Unnamed: 19
0  Cheatham    0          0             1 -87.080007   36.31388      2           2    7.23                  4.56          NaN             NaN          NaN          NaN          NaN          NaN          NaN          NaN    Cheatham          NaN
1  Cheatham    0          0             2 -87.247114  36.366981      0           0  116.98                  0.00          NaN             NaN          NaN          NaN          NaN          NaN          NaN          NaN           0          NaN
2  Cheatham    0          0             3 -87.026783  36.182776      1           1    0.22                  2.30          NaN             NaN          NaN          NaN          NaN          NaN          NaN          NaN  Montgomery          NaN
3  Cheatham    0          0             4 -87.116023  36.309677      2           2    1.54                  5.17          NaN             NaN          NaN          NaN          NaN          NaN          NaN          NaN         NaN          NaN
4  Cheatham    0          0             5 -87.130918  36.279787      0           0    0.00                  0.00          NaN             NaN          NaN          NaN          NaN          NaN          NaN          NaN     Dickson          NaN
Sheet Name: Run 35 - parcel forecast 50UGB
     County City Unnamed: 2  geo_level_id          x          y  units  households    jobs  household_population  Unnamed: 10  04/11/2025 run
0  Cheatham    0          0           1.0 -87.080007   36.31388    3.0         3.0    7.22                  7.47          NaN             NaN
1  Cheatham    0          0           2.0 -87.247114  36.366981    0.0         0.0  117.30                  0.00          NaN             NaN
2  Cheatham    0          0           3.0 -87.026783  36.182776    1.0         1.0    0.54                  2.29          NaN             NaN
3  Cheatham    0          0           4.0 -87.116023  36.309677    2.0         2.0    2.30                  5.20          NaN             NaN
4  Cheatham    0          0           5.0 -87.130918  36.279787    0.0         0.0    0.10                  0.00          NaN             NaN

In [6]:
parcel_lookup = data['parcel lookup']

In [7]:
#NAME is Census Place
#NAMELSAD is County
#Name is name of UGB: urban growth boundary, PGA: planned growth area
parcel_lookup.head()

   OBJECTID * Shape *  Join_Count  TARGET_FID  urbansim_r          X          Y       X_LP       Y_LP NAME  NAMELSAD   Shape_Length         Name Type
0      669347   Point           1      669346       15324 -87.013953  36.135439 -87.013953  36.135439  NaN  Cheatham  953969.243122  Peagram UGB  UGB
1      669350   Point           1      669349       15351 -87.011172  36.135244 -87.011172  36.135244  NaN  Cheatham  953969.243122  Peagram UGB  UGB
2      669352   Point           1      669351       15330 -87.013097  36.134054 -87.013097  36.134054  NaN  Cheatham  953969.243122  Peagram UGB  UGB
3      669353   Point           1      669352       15350 -87.009619  36.134734 -87.009619  36.134734  NaN  Cheatham  953969.243122  Peagram UGB  UGB
4      669354   Point           1      669353       15273 -87.012648  36.132675 -87.012648  36.132675  NaN  Cheatham  953969.243122  Peagram UGB  UGB

In [9]:
#parcel_lookup['Type'].unique()

array(['UGB', 'PGA', nan], dtype=object)

# Sheet Names

+ SUB-IP-EST2023-POP-47: 2023 vintage pop estimates for incorporated places in Tennessee, years 2020 through 2023  
+ parcel lookup: each parcel tagged to a place, county, ugb/pga/none, with size and centroids  
+ Run X - parcel forecast 2023:

In [11]:


# Read the Parquet file into a DataFrame
df = pd.read_parquet('../data/urbansim/20250512-181347-47197701-dcuncivfhlt8g6je9nfa-sim-results.parquet')

# Print the DataFrame
df.head()

   year geo_level     geo_level_id          indicator_id  indicator_value
0  2023     block  470831203003000  sum_total_households              9.0
1  2023     block  470831203003090  sum_total_households              0.0
2  2023     block  471190103013047  sum_total_households              0.0
3  2023     block  471690902001031  sum_total_households             32.0
4  2023     block  471190112003048  sum_total_households              1.0

In [12]:
df['year'].unique()

array([2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033,
       2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044,
       2045, 2046, 2047, 2048, 2049, 2050])

In [13]:
df['geo_level'].unique()

array(['block', 'tract', 'block_group', 'region', 'county', 'municipal'],
      dtype=object)

In [14]:
df['indicator_id'].unique()

array(['sum_total_households', 'household_population', 'sum_total_units',
       'sum_total_jobs', 'residential_price', 'density_households_acre',
       'household_population_density_acres', 'density_units_acre',
       'density_jobs_acre', 'rent_burden', 'severe_rent_burden',
       'percentage_rent_burden', 'percentage_severe_rent_burden',
       'rental_units', 'own_units', 'renters_vacancy_rate',
       'owners_vacancy_rate', 'residential_capacity',
       'employment_capacity', 'sector_0', 'sector_1', 'sector_2',
       'sector_3', 'sector_4', 'sector_5', 'sector_6', 'sector_7',
       'sector_8', 'ln_price_own_county_47037',
       'prop_parcel_area_in_wetlands_county_other',
       'ln_price_own_county_other', 'ln_acres_county_other',
       'prop_parcel_area_slope_gt14_03_degrees_county_47037',
       'prop_parcel_area_slope_gt8_53_degrees_county_other',
       'ln_unit_county_other', 'prop_lowinc_county_other',
       'ln_job_access_10_miles_county_47037',
       'prop_parcel_area_slope_gt11_3_degrees_county_other',
       'prop_parcels_in_100_year_flood_plain_county_other',
       'ln_job_access_1_miles_county_47037',
       'prop_parcel_area_slope_gt8_53_degrees_county_47037',
       'ln_unit_county_47037',
       'prop_parcel_area_in_wetlands_county_47037',
       'ln_job_access_10_miles_county_other',
       'mean_parcel_slope_county_other', 'prop_lowinc_county_47037',
       'ln_job_access_1_miles_county_other', 'ln_acres_county_47037',
       'prop_parcel_area_slope_gt14_03_degrees_county_other',
       'prop_parcels_in_100_year_flood_plain_county_47037',
       'prop_parcel_area_slope_gt11_3_degrees_county_47037',
       'mean_parcel_slope_county_47037'], dtype=object)

So I'm taking the sample download of parcel data from UrbanSim and using the parcel lookup to populate the SmallArea and the Summary_w_UGB.