In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)

In [5]:
parcels = gpd.read_file('../data/Geo/ParcelCenterPts_projected.shp')

In [6]:
#parcels_proj = parcels.to_crs(epsg=26916)

In [7]:
parcels.head()

    COUNTY          GISLINK  GISLINK_X  GISLINK_Y          X          Y                        geometry
0  STEWART  081055    00401   4.016667   8.181944 -87.800331  36.554674  POINT (1439711.524 813466.205)
1   WILSON  095016    00100   1.000000   9.837778 -86.287792  36.326106  POINT (1883722.463 725513.148)
2   WILSON  095115    02401  24.016667   9.854167 -86.344029  36.102465  POINT (1866869.567 644152.603)
3   WILSON  095019    00805   8.083333   9.838611 -86.169753  36.321454  POINT (1918491.722 723738.057)
4  STEWART  081140    00310   3.166667   8.194444 -87.627314  36.369018  POINT (1489401.120 744994.011)

In [8]:
schools = gpd.read_file('../data/Geo/Schools_Projected.shp')

In [9]:
schools.head()

,OBJECTID_1,NCESSCH,SURVYEAR,STABR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,LSTREET1,LSTREET2,LCITY,LSTATE,LZIP,LZIP4,PHONE,CHARTER_TE,MAGNET_TEX,VIRTUAL,GSLO,GSHI,SCHOOL_LEV,TITLEI_TEX,TITLEI,STITLEI,STATUS,SCHOOL_TYP,SY_STATUS_,ULOCALE,NMCNTY,TOTFRL,FRELCH,REDLCH,DIRECTCERT,PK,KG,G01,G02,G03,G04,G05,G06,G07,G08,G09,G10,G11,G12,G13,UG,AE,TOTMENROL,TOTFENROL,TOTAL,MEMBER,FTE,STUTERATIO,AMALM,AMALF,AM,ASALM,ASALF,AS_,BLALM,BLALF,BL,HPALM,HPALF,HP,HIALM,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD,geometry
0,79275,470000100477,2021-2022,TN,4700001,TN-00320,Hamblen County,Alpha Elementary,5620 Old Us 11e HWY,None,Morristown,TN,37814,None,(423)586-3332,No,No,Not Virtual,KG,05,Elementary,4-Title I schoolwide eligible school-No program,1-Yes,1-Yes,1,Regular school,Currently operational,13-City: Small,Hamblen County,0,0,0,137,0,81,91,79,106,101,108,0,0,0,0,0,0,0,0,0,0,None,None,566,566,37.000000,15.30,0,0,0,14,12,26,3,7,10,6,2,8,19,21,40,20,21,41,223,218,441,36.177827,-83.386666,POINT (2739700.011 681705.434)
1,79276,470000100479,2021-2022,TN,4700001,TN-00320,Hamblen County,East Ridge Middle School,6595 St. Clair RD,None,Whitesburg,TN,37891,None,(423)581-3041,No,No,Supplemental Virtual,06,08,Middle,4-Title I schoolwide eligible school-No program,1-Yes,1-Yes,1,Regular school,Currently operational,41-Rural: Fringe,Hamblen County,0,0,0,108,0,0,0,0,0,0,0,168,182,168,0,0,0,0,0,0,0,None,None,518,518,33.500000,15.46,1,1,2,2,2,4,4,5,9,0,1,1,22,19,41,7,17,24,226,211,437,36.267200,-83.183800,POINT (2798614.034 715888.019)
2,79277,470000100480,2021-2022,TN,4700001,TN-00320,Hamblen County,Fairview Marguerite,2125 Fairview RD,None,Morristown,TN,37814,None,(423)586-4098,No,No,Not Virtual,KG,05,Elementary,5-Title I schoolwide school,1-Yes,1-Yes,1,Regular school,Currently operational,13-City: Small,Hamblen County,0,0,0,160,0,79,79,58,73,83,79,0,0,0,0,0,0,0,0,0,0,None,None,451,451,34.639999,13.02,0,1,1,3,1,4,2,4,6,1,1,2,153,147,300,9,3,12,62,64,126,36.236800,-83.292400,POINT (2766917.200 703921.927)
3,79278,470000100481,2021-2022,TN,4700001,TN-00320,Hamblen County,Manley Elementary,551 West Economy RD,None,Morristown,TN,37814,None,(423)586-7400,No,No,Not Virtual,PK,05,Elementary,4-Title I schoolwide eligible school-No program,1-Yes,1-Yes,1,Regular school,Currently operational,13-City: Small,Hamblen County,0,0,0,143,87,88,77,91,84,88,85,0,0,0,0,0,0,0,0,0,0,None,None,600,600,37.250000,16.11,1,0,1,10,6,16,9,11,20,7,5,12,76,78,154,31,11,42,199,156,355,36.208655,-83.337658,POINT (2753853.553 693313.649)
4,79279,470000100483,2021-2022,TN,4700001,TN-00320,Hamblen County,Russellville Elementary,5655 Old Russellville PIKE,None,Russellville,TN,37860,None,(423)586-6560,No,No,Not Virtual,PK,05,Elementary,4-Title I schoolwide eligible school-No program,1-Yes,1-Yes,1,Regular school,Currently operational,23-Suburb: Small,Hamblen County,0,0,0,114,80,95,97,91,100,85,81,0,0,0,0,0,0,0,0,0,0,None,None,629,629,39.639999,15.87,0,0,0,5,1,6,3,4,7,0,0,0,36,17,53,20,21,41,265,257,522,36.254400,-83.203900,POINT (2792824.021 711060.264)

In [10]:
# schools_proj = schools.to_crs("EPSG:4326")
# schools_proj = schools_proj.to_crs(epsg=26916)

In [11]:
schools.crs

<Projected CRS: EPSG:6576>
Name: NAD83(2011) / Tennessee (ftUS)
Axis Info [cartesian]:
- X[east]: Easting (US survey foot)
- Y[north]: Northing (US survey foot)
Area of Use:
- name: United States (USA) - Tennessee - counties of Anderson; Bedford; Benton; Bledsoe; Blount; Bradley; Campbell; Cannon; Carroll; Carter; Cheatham; Chester; Claiborne; Clay; Cocke; Coffee; Crockett; Cumberland; Davidson; De Kalb; Decatur; Dickson; Dyer; Fayette; Fentress; Franklin; Gibson; Giles; Grainger; Greene; Grundy; Hamblen; Hamilton; Hancock; Hardeman; Hardin; Hawkins; Haywood; Henderson; Henry; Hickman; Houston; Humphreys; Jackson; Jefferson; Johnson; Knox; Lake; Lauderdale; Lawrence; Lewis; Lincoln; Loudon; Macon; Madison; Marion; Marshall; Maury; McMinn; McNairy; Meigs; Monroe; Montgomery; Moore; Morgan; Obion; Overton; Perry; Pickett; Polk; Putnam; Rhea; Roane; Robertson; Rutherford; Scott; Sequatchie; Sevier; Shelby; Smith; Stewart; Sullivan; Sumner; Tipton; Trousdale; Unicoi; Union; Van Buren; Warren; Washington; Wayne; Weakley; White; Williamson; Wilson.
- bounds: (-90.31, 34.98, -81.65, 36.68)
Coordinate Operation:
- name: SPCS83 Tennessee zone (US Survey feet)
- method: Lambert Conic Conformal (2SP)
Datum: NAD83 (National Spatial Reference System 2011)
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [16]:
test = gpd.sjoin_nearest(parcels, schools, how = 'inner', max_distance = None, lsuffix = 'Parcels ', rsuffix = 'Schools ', distance_col = 'Distance')

In [17]:
test.head()

,COUNTY,GISLINK,GISLINK_X,GISLINK_Y,X,Y,geometry,index_Schools,OBJECTID_1,NCESSCH,SURVYEAR,STABR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,LSTREET1,LSTREET2,LCITY,LSTATE,LZIP,LZIP4,PHONE,CHARTER_TE,MAGNET_TEX,VIRTUAL,GSLO,GSHI,SCHOOL_LEV,TITLEI_TEX,TITLEI,STITLEI,STATUS,SCHOOL_TYP,SY_STATUS_,ULOCALE,NMCNTY,TOTFRL,FRELCH,REDLCH,DIRECTCERT,PK,KG,G01,G02,G03,G04,G05,G06,G07,G08,G09,G10,G11,G12,G13,UG,AE,TOTMENROL,TOTFENROL,TOTAL,MEMBER,FTE,STUTERATIO,AMALM,AMALF,AM,ASALM,ASALF,AS_,BLALM,BLALF,BL,HPALM,HPALF,HP,HIALM,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD,Distance
0,STEWART,081055 00401,4.016667,8.181944,-87.800331,36.554674,POINT (1439711.524 813466.205),1649,80924,470396002093,2021-2022,TN,4703960,TN-00810,Stewart County,Stewart County Adult High School,120 Robertson Hill RD,None,Dover,TN,37058,None,(931)232-5179,No,No,Not Virtual,09,12,High,6-Not a Title I school,2-No,N,1,Regular school,Currently operational,42-Rural: Distant,Stewart County,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,None,None,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,36.531824,-87.814891,9354.415394
855,STEWART,081046 00400,4.000000,8.179444,-87.862147,36.576743,POINT (1421710.152 821839.431),1649,80924,470396002093,2021-2022,TN,4703960,TN-00810,Stewart County,Stewart County Adult High School,120 Robertson Hill RD,None,Dover,TN,37058,None,(931)232-5179,No,No,Not Virtual,09,12,High,6-Not a Title I school,2-No,N,1,Regular school,Currently operational,42-Rural: Distant,Stewart County,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,None,None,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,36.531824,-87.814891,21450.769795
1359,STEWART,081018 00200,2.000000,8.171667,-87.858261,36.626324,POINT (1423193.906 839866.365),1649,80924,470396002093,2021-2022,TN,4703960,TN-00810,Stewart County,Stewart County Adult High School,120 Robertson Hill RD,None,Dover,TN,37058,None,(931)232-5179,No,No,Not Virtual,09,12,High,6-Not a Title I school,2-No,N,1,Regular school,Currently operational,42-Rural: Distant,Stewart County,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,None,None,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,36.531824,-87.814891,36687.371844
1443,STEWART,081045 01802,18.033333,8.179167,-87.818725,36.565295,POINT (1434381.506 817432.474),1649,80924,470396002093,2021-2022,TN,4703960,TN-00810,Stewart County,Stewart County Adult High School,120 Robertson Hill RD,None,Dover,TN,37058,None,(931)232-5179,No,No,Not Virtual,09,12,High,6-Not a Title I school,2-No,N,1,Regular school,Currently operational,42-Rural: Distant,Stewart County,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,None,None,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,36.531824,-87.814891,12238.205445
1444,STEWART,081045 01802,18.033333,8.179167,-87.818725,36.565295,POINT (1434381.506 817432.474),1649,80924,470396002093,2021-2022,TN,4703960,TN-00810,Stewart County,Stewart County Adult High School,120 Robertson Hill RD,None,Dover,TN,37058,None,(931)232-5179,No,No,Not Virtual,09,12,High,6-Not a Title I school,2-No,N,1,Regular school,Currently operational,42-Rural: Distant,Stewart County,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,None,None,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,36.531824,-87.814891,12238.205445

In [18]:
test.to_file('../data/Geo/test.shp')

C:\Users\jmccall\AppData\Local\Temp\ipykernel_18896\2221609178.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  test.to_file('../data/Geo/test.shp')